### ISSUE TITLE
ImportError: No module named 'pyexpat'

### ISSUE THREAD

**Issue by StarkBall** [video-dl/video-dl-ios#15]
I try to build on iPhone6 whose SDK is iOS8.
By modify the compile.py, I can build the library and run on iPhone6 successfully.

However, when I try to test download, it also display this log

```
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Extracting video information
[youtube] BaW_jenozKc: Downloading DASH manifest
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/pylib/lib/xml/etree/ElementTree.py", line 1515, in __init__
    from xml.parsers import expat
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/pylib/lib/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/pylib/lib/xml/etree/ElementTree.py", line 1518, in __init__
    import pyexpat as expat
ImportError: No module named 'pyexpat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/modules/youtube_dl/YoutubeDL.py", line 619, in extract_info
    ie_result = ie.extract(url)
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/modules/youtube_dl/extractor/common.py", line 267, in extract
    return self._real_extract(url)
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/modules/youtube_dl/extractor/youtube.py", line 1084, in _real_extract
    video_id, dash_manifest_url, player_url, age_gate)
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/modules/youtube_dl/extractor/youtube.py", line 758, in _parse_dash_manifest
    errnote='Could not download DASH manifest')
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/modules/youtube_dl/extractor/common.py", line 418, in _download_xml
    return xml.etree.ElementTree.fromstring(xml_string.encode('utf-8'))
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/pylib/lib/xml/etree/ElementTree.py", line 1355, in XML
    parser = XMLParser(target=TreeBuilder())
  File "/private/var/mobile/Containers/Bundle/Application/811DDCD1-2058-41CB-99CF-C3FC90C58B1A/video-dl.app/python/pylib/lib/xml/etree/ElementTree.py", line 1521, in __init__
    "No module named expat; use SimpleXMLTreeBuilder instead"
ImportError: No module named expat; use SimpleXMLTreeBuilder instead
```

Do you have any idea?

**Comment by jaimeMF** [comment]
It doesn't compile the C xml module, I need to add it.

**Comment by StarkBall** [comment]
Thanks for reply.

Could you give me some hints, and I can try it?

**Comment by jaimeMF** [comment]
It should be fixed now, thanks for the report.

**Comment by StarkBall** [comment]
Nice!
Thanks a lot!
